### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by dcousens** [markmarijnissen/cordova-plugin-share#6]
Hi @markmarijnissen!

I was just wonder if there is any reason you haven't published this to `npm` yet?

**Comment by markmarijnissen** [comment]
I'm very busy - it's hard for me to maintain this project. Is there anybody willing to become collaborator on this Github project? (Is it possible for multiple people to publish to NPM?). Help appreciated!!

**Comment by dcousens** [comment]
@markmarijnissen sure, I'm happy to help.

> Is it possible for multiple people to publish to NPM?

`npm owner add USERNAME`

**Comment by dcousens** [comment]
bump @markmarijnissen

**Comment by code2be** [comment]
I'm done publishing to NPM: https://www.npmjs.com/package/cordova-plugin-share

**Comment by compelling** [comment]
@code2be when i fetch the plugin from NPM, i the wrong version, it seems.
This is how i fetch it from my config.xml
`<plugin name="cordova-plugin-share" source="npm" spec="0.1.2" />`
I get a crash on iPad, which should be fixed in the plugin in the last version.
If i fetch the plugin from git, sharing works on iPad.
cordova plugins add https://github.com/markmarijnissen/cordova-plugin-share.git
It's easy to see the problem, in src/ios/MMShare.m there there is a comment about a IOS8 fix - this comment is not there when pulling latest version from NPM.

**Comment by code2be** [comment]
@compelling Do You mean this commit https://github.com/markmarijnissen/cordova-plugin-share/commit/f1c5a4346af18feb498d47626e66afd757285d71 ?
As seems to be done after my being published it to NPM.

**Comment by compelling** [comment]
@code2be Aah, right, now i see that. Could you publish an 0.1.3 on NPM with that commit?

**Comment by code2be** [comment]
@compelling Sure, Let me just review to remember which modifications I did while publishing to NPM, and merge with the latest commit mentioned.

**Comment by singuyenhoang** [comment]
@code2be : Could you please help publish 0.1.3 on NPM ?
We really need this available on NPM now.
My project is depending on PhoneGapBuild :(

**Comment by code2be** [comment]
@singuyenhoang Sorry for the delay, Done publishing 0.1.3 to NPM this Morning.

**Comment by dcousens** [comment]
Thanks @code2be
